[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fanplay = "CyDt5Z3G4vaD15SXeGmGJc3yqPoej7PpqMP2fjkpGYhn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --paths -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
